server:
  build: server
  ports:
   - "8082:8082"
  environment:
   - NODE_ENV=production
   - PORT=8082
  volumes:
   - ./server/temp/:/app/temp


client:
  image: nginx:1.11.4-alpine
  volumes:
   - ./client/build/:/usr/share/nginx/html
   - ./client/nginx.conf:/conf.conf
  ports:
   - "8083:8080"
  environment:
   - NAME=www.volpe.com.py
   - PORT=8080
   - URI=uri
  command: /bin/sh -c "cat /conf.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

